#!/bin/bash
for i in {0..13}
do
    ./samplewc209 < ./tests/input/test$i.txt > ./output/outputsa$i 2> ./output/errorsa$i
    ./wc209 < ./tests/input/test$i.txt > ./output/outputmy$i 2> ./output/errorsmy$i
    echo "$i: "
    diff ./output/outputsa$i ./output/outputmy$i
    diff ./output/errorsa$i ./output/errorsmy$i
    # rm output1 output2 errors1 errors2
done