#!/bin/bash
gcc209 -c -g -O0 -no-pie -o mydc.o mydc.s
gcc209 -no-pie -o mydc mydc.o
echo "----------test_start----------"
for i in {1..9}
do
    echo "jhtest0$i"
    ./mydc < ./tests/jhtest/jhtest0$i.txt >stdout 2>stderr
    diff ./tests/jhtest/jhtest0$i.stdout stdout
    diff ./tests/jhtest/jhtest0$i.stderr stderr
done
for i in {10..79}
do
    echo "jhtest$i"
    ./mydc < ./tests/jhtest/jhtest$i.txt >stdout 2>stderr
    diff ./tests/jhtest/jhtest$i.stdout stdout
    diff ./tests/jhtest/jhtest$i.stderr stderr
done
echo "----------test_done----------"